import = [
  "~/alacritty-themes/cyber_china.toml"
]

[window]
dimensions = { columns = 120, lines = 20 }
decorations = "Full"
#opacity = 0.95
opacity = 1
blur = true

[font]
normal = { family = "FiraCode Nerd Font", style = "medium" }

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 100

[keyboard]
#bindings = [{ <key>, <mods>, <mode>, <action> | <chars> },]
#bindings = [{ key = "n", mods = "Control | Shift", action = "CreateNewWindow" },]

[selection]
save_to_clipboard = true



